[package]
name = "rust"
version = "0.1.0"
authors = ["Evgeny Fomin <fominok@hotmail.com>"]
edition = "2018"

[dependencies]
rustyline = "3.0.0"
regex = "1.1.5"
lazy_static = "1.3.0"

[[bin]]
name = "step0_repl"
path = "step0_repl.rs"

[[bin]]
name = "step1_read_print"
path = "step1_read_print.rs"
